apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gmail-rules-alert-config
  namespace: sre
spec:
  route:
    group_wait: 10s
    group_interval: 2m
    receiver: 'gmail-notifications'
    repeat_interval: 2m
  receivers:
  - name: 'gmail-notifications'
    email_configs:
    - to: example@gmail.com 
      from: taiwolawal360@gmail.com # Update your from mail id here
      smarthost: smtp.gmail.com:587
      auth_username: taiwolawal360@gmail.com # Update your from mail id here
      auth_identity: taiwolawal360@gmail.com # Update your from mail id here
      authPassword:
        name: gmail-auth
        key: password
      send_resolved: true
      headers:
        subject: " Prometheus -  Alert  "
      text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "
